config/routes.rb
Rails.application.routes.draw do

  resources :events, only: [:new, :create, :show, :index, :destroy]
  root to: 'events#index'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :event_users, only: [:index, :show, :update, :destroy]

  resources :event_users do
    match '/join', to: 'event_user#join', via: :post, on: :collection
  end
  
  resources :users, only: [:index, :show, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :description, :location, :date, presence: true

  scope :coming_events, -> { where('date >= ?', Date.today) }
  scope :prev_events, -> { where('date < ?', Date.today) }

  belongs_to :creator, class_name: 'User'
  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users, source: :user
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id', dependent: :destroy
  has_many :event_users, dependent: :destroy
  has_many :events, through: :event_users, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_user_controller.rb
class EventUserController < ApplicationController
  def join
    @event_users = EventUser.new(event_id: params[:id], user_id: current_user.id)
    @event_users.save
    redirect_to events_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.all
    @coming_events = Event.coming_events
    @prev_events = Event.prev_events
  end

  def show
    @event = Event.find(params[:id])
    @users = @event.users
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: 'Your event was created'
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def display_coming
    @coming_events = Event.coming_events
  end

  def display_prev
    @prev_events = Event.prev_events
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :location, :description)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if signed_in?
      @created_events = current_user.created_events
      @events = current_user.events
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    redirect_to users_path if @user.save
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_registration(event)
    if event.event_users.exists?(user_id: current_user.id)
      '<h5>Already signed in</h5>'.html_safe
    else
      (link_to 'Join', join_event_users_path(id: @event.id), method: :post).to_s.html_safe
    end
  end

  def create_event_link
    return unless current_user

    (link_to 'Create new event', new_event_path).to_s.html_safe
  end

  def display_name(event)
    if signed_in?
      "<h4>Created by #{event.creator.name}</h4>".html_safe
    else
      '<h4>Created by Anonymous</h4>'.html_safe
    end
  end

  def event_goers(users)
    result = '<p>No attendees yet</p>'
    unless @users.count.zero?
      result = ''
      users.each do |user|
        result += "<h2>#{user.name}<h2>".html_safe
      end
    end
    result.html_safe
  end

  def user_signs(*)
    if signed_in?
      "Signed in as [ #{link_to current_user.name, user_path(current_user)} ]
        #{link_to 'Sign out', destroy_user_session_path, method: :delete}".html_safe
    else
      "<p'>
      #{link_to 'Sign In in / Sign up', new_user_registration_path}
    </p>".html_safe
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
 <h2>Listing All the previous events</h2>
    <%@prev_events and @prev_events.each do |event| %>
          <h3><%= event.title %></h3> 
          <p><%= event.description %></p> <br>
          <%= link_to 'Show more', event_path(event) %> <br>
          Created at <%= (event.created_at) %> 
    <% end %>


  <h2>Listing All the coming events</h2>
    <%@coming_events and @coming_events.each do |event| %>
          <h3><%= event.title %></h3> 
          <p><%= event.description %></p> <br>
          <%= link_to 'Show more', event_path(event)%> <br>
          Created at <%= (event.created_at) %> 
    <% end %>

    <br><br>

  <%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>


    <p>Event title :</p>
    <h1><%= @event.title.titleize %></h1>

    <p>Created by :</p>
    <h5>
      <%= @event.creator.name %>
    </h5>
    <p>Date :</p>
    <h5><%= @event.date.strftime("%d %b, %Y at %l:%M %p") %></h5> 

 <p>Location :</p>
    <h5><%= @event.location %></h5>

        <h2>Description</h2>
        <p><%= @event.description %></p>

      <%= show_registration(@event) %>

 <% if current_user == @event.creator %>
      <%= link_to 'Delete', event_path, method: :delete, data: { confirm: "Delete this event?"} %>
    <% end %>      

 <h2> All Attendees</h2>
        <%= event_goers(@users)  %>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <i><%= link_to "The Events", events_path %></i>
    
          <%= link_to 'The Members', users_path %>
        
          <%= create_event_link %>
         <%= user_signs(current_user) %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
    <% @users.each do |user| %>
          <h2><%= user.name %></h2>
          <h5><%= user.email %></h5>
          <p>All Created events - <%= user.created_events.count %> </p>
          <p>All Joined events - <%= user.event_users.count %> </p>
    <% end %>
  

app/views/users/show.html.erb
  <h1><%= current_user.name %> All Created events</h1>

  <% if user_signed_in? %>
    <h4>Created events - <%= @created_events.count %></h4>
    <% @created_events.each do |event| %>
          <h2><%= event.title %></h2>
          <%= display_name(event) %>
          <p><%= truncate(event.description,length:20) %></p>
          <%= link_to 'Show more', event_path(event) %>
          Created at <%= (event.created_at) %> 
    <% end %>
  <h4>All Attended events - <%= @events.count %></h4>
    <% @events.each do |event| %>
          <h2><%= event.title %></h2>
          <%= display_name(event) %>
          <p><%= truncate(event.description,length:20) %></p>
          <%= link_to 'Show more', event_path(event)%>
          Created at <%= (event.created_at) %> ago
    <% end %>
    
 <h2>Listing All the previous events</h2>
    <%@prev_events and @prev_events.each do |event| %>
          <h3><%= event.title %></h3> 
          <p><%= event.description %></p> <br>
          <%= link_to 'Show more', event_path(event) %> <br>
          Created at <%= (event.created_at) %> 
    <% end %>


  <h2>Listing All the coming events</h2>
    <%@coming_events and @coming_events.each do |event| %>
          <h3><%= event.title %></h3> 
          <p><%= event.description %></p> <br>
          <%= link_to 'Show more', event_path(event)%> <br>
          Created at <%= (event.created_at) %> 
    <% end %>

  <% end %>

  